pipeline {
    agent{
        label "netx-serg"
    }

    stages{
        stage("Install"){
            steps{
                sh """
                    git pull
                    npm install
                """
            }
        }
        stage("Build"){
            steps{
                sh """
                    npm run build
                """
            }
        }
        stage("Start"){
            steps{
                sh """
                    pm2 restart next.slipchuk.site
                """
            }
        }
    }
}