pipeline {
    agent{
        label "${NETX_WORKER}"
    }

    stages{
        stage("Install"){
            steps{
                sh """
                    pm2 stop ${NEXTJS_DOMAIN}
                    cd ${NEXTJS_FOLDER}
                    pwd
                    git pull
                    npm install
                """
            }
        }
        stage("Build"){
            steps{
                sh """
                    cd ${NEXTJS_FOLDER}
                    pwd
                    npm run build
                """
            }
        }
        stage("Start"){
            steps{
                sh """
                    pm2 restart ${NEXTJS_DOMAIN}
                """
            }
        }
    }
}